# Generated by Django 3.1.1 on 2020-09-09 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='text',
            new_name='notes',
        ),
    ]
