# Generated by Django 3.1.1 on 2020-09-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_app', '0002_auto_20200911_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
